### PR TITLE
Correct namespace for tests

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1224

** DO NOT MERGE FIRST **

The sequence for the related PRs is

*  this PR
*  update Crayfish PR to direct to dev-symfony-flex branch
*  Merge https://github.com/Islandora/Crayfish/pull/102
*  Merge https://github.com/Islandora-Devops/ansible-role-crayfish/pull/34
*  cut a new version of Crayfish role, update islandora-playbook PR
*  Merge https://github.com/Islandora-Devops/islandora-playbook/pull/175

# What does this Pull Request do?

This really does nothing other than update the symfony version and composer packages, fix the tests namespaces for autoload and a change in how a ClientException is constructed.

# How should this be tested?

This is used as part of above PRs, if that passes then this could be merged.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by rosiel** [comment]
@whikloj are you still waiting on someone to help out with this?

**Comment by whikloj** [comment]
@rosiel yes, if there is still a desire to transition from Flex to Symfony.

**Comment by elizoller** [comment]
@whikloj i can give a shot at testing this - would this be the first PR in the sequence?

**Comment by whikloj** [comment]
I believe so yes. Not that anyone uses the playbook anymore but this (https://github.com/Islandora-Devops/islandora-playbook/pull/175) pulled in all individual branches.

**Comment by elizoller** [comment]
To test this I did the following:
1. spun up a playbook
2. in composer.json at the islandora root, aliased this branch as dev-dev and ran composer update
3. ran the tests in crayfish-commons
4. verified no composer dependency issues
5. verified an object could be saved to fedora
I think that is sufficient.
Any complaints?

**Review by elizoller — APPROVED** [review]
1. spun up a playbook
2. in composer.json at the islandora root, aliased this branch as dev-dev and ran composer update
3. ran the tests in crayfish-commons
4. verified no composer dependency issues
5. verified an object could be saved to fedora

**Pull request merged**
