### PR TITLE
consider  as uri if it is not a resource

### PR DESCRIPTION
**Pull request by Natkeeran**
**GitHub Issue**: (link)
https://github.com/Islandora-CLAW/CLAW/issues/943

# What does this Pull Request do?
This PR will tell Crayfish-Commons to not to load $data into the pipe if it is not a resource.  It is assumed that a resource url will be passed in.  Specifically to address the above 943 ffmpeg issue.

# How should this be tested?
This needs to be tested other related PRs.  Which I will post shortly here.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-CLAW/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
`phpcbf` can take care of Travis: https://travis-ci.com/Islandora-CLAW/Crayfish-Commons/jobs/156095121

**Comment by dannylamb** [comment]
linking to https://github.com/Islandora-CLAW/Crayfish/pull/52

**Comment by dannylamb** [comment]
Codecov forced me to use admin privileges to merge that because coverage dropped by a tiny percentage.  I should go through our repos and disable that so it's not a 'required' status check and instead just a tool of guilt.

**Comment by dannylamb** [comment]
Eww... so I don't know if I can do that...

It's either required or not a status check at all.  I wonder if it will still run when not a status check?  Only one way to find out.

**Comment by whikloj** [comment]
It won't run, we should keep it as required and figure out why coverage dropped and add tests so it doesn't.

**Comment by whikloj** [comment]
Actually we have no tests for the `CmdExecuteService` so adding **any** complexity to it reduces the overall coverage. We should add tests for this service.

**Pull request merged**
